spring.application.name=school
spring.datasource.url= jdbc:postgresql://localhost:5432/hogwarts
spring.datasource.username= student
spring.datasource.password= qweqwe
spring.jpa.hibernate.ddl-auto= update

path.to.avatars.folder = ./data/media/avatars
avatar.size.max.kb = 300
avatar.scaling.db = 10
avatar.height.min = 100
avatar.width.min = 100